### PR TITLE
Add resource azurerm_cdn_frontdoor_secret

### LINKED ISSUE #4: [FEAT] Create azurerm_cdn_frontdoor_secret based on existing keyvault certificate
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In order for a custom domain to support an imported certificate, a parameter specifying which keyvault certificate ID is required and a new resource azurerm_cdn_frontdoor_secret is also required.
This allows users to import their own certificate into keyvault and deploy it as part of a Front Door custom domain.

### New or Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_secret

### Potential Terraform Configuration

```hcl
# NOTE: In order for the certificate to be used by Azure FrontDoor, it must be PKCS#12 PFX 3DES.
# openssl pkcs12 -export -out cert.pfx -inkey host-private.key -in leaf.pem -certfile intermediate.pem -legacy
#
resource "azurerm_key_vault_certificate" "cert" {
  name         = local.server_fqdn
  key_vault_id = local.key_vault_id

  certificate {
    contents = filebase64("./cert.pfx")
    password = ""
  }

  # The following is required for PFX imports, but not PEM.
  certificate_policy {
    issuer_parameters {
      name = "Unknown"
    }
    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = false
    }
    secret_properties {
      content_type = "application/x-pkcs12"
    }
  }

}

module "cdn-frontdoor" {

  custom_domains = [
    {
      name      = local.server
      host_name = local.server_fqdn
      tls = {
        certificate_type         = "CustomerCertificate"
        key_vault_certificate_id = azurerm_key_vault_certificate.cert.id
      }
    }
  ]

}
```

### References

[FrontDoor HTTPS with your own certificate](https://learn.microsoft.com/en-us/azure/frontdoor/standard-premium/how-to-configure-https-custom-domain?tabs=powershell#use-your-own-certificate)

### PR DESCRIPTION
**Pull request by blongv**
Fixes #4 .

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Changes proposed in this pull request

- Create resource azurerm_cdn_frontdoor_secret if custom_domains.key_vault_certificate_id is defined.
- Use the secret as azurerm_cdn_frontdoor_custom_domain.cdn_frontdoor_secret_id.

@claranet/fr-azure-reviewers

### CODE REVIEW

**Review by Shr3ps — CHANGES_REQUESTED** [review]
Can you please update or add an example with this new feature?
Also, you need to update the README file with terraform-docs (CI is failing)

**Comment by blongv** [comment]
> Can you please update or add an example with this new feature? Also, you need to update the README file with terraform-docs (CI is failing)

The issue #4 has an example.  I just submitted the README fix after installing your pre-commit hooks.  Thanks for reviewing.

**Comment by Shr3ps** [comment]
> > Can you please update or add an example with this new feature? Also, you need to update the README file with terraform-docs (CI is failing)
> 
> The issue #4 has an example. I just submitted the README fix after installing your pre-commit hooks. Thanks for reviewing.

Thanks for the README update!
About the example, I mean it would be nice if you can update the `examples/main/modules.tf` file (and run pre-commit again for the README update) with the elements you put in the issue.
It will be helpful for users/people who use our module.

**Comment by blongv** [comment]
>  About the example, I mean it would be nice if you can update the `examples/main/modules.tf` file (and run pre-commit again for the README update) with the elements you put in the issue. It will be helpful for users/people who use our module.

I apologize because I am not very familiar with pre-commit errors mentioning files outside this git project like the following:
```
$ git commit -am 'chore: update example for custom domains'
trim trailing whitespace................................................................Passed
fix end of files........................................................................Passed
check json..........................................................(no files to check)Skipped
check yaml..........................................................(no files to check)Skipped
check for broken symlinks...........................................(no files to check)Skipped
check for added large files.............................................................Passed
detect private key......................................................................Passed
Terraform fmt...........................................................................Passed
Terraform docs......................................................(no files to check)Skipped
Terraform validate..................................................(no files to check)Skipped
Terraform validate with tflint......................................(no files to check)Skipped
Terraform validate with tfsec (deprecated, use "terraform_trivy").......................Passed
error: invalid object 100644 496b1048c932a54707cbd671fb29e27c16197509 for 'examples/automation-account/README.md'
error: Error building trees
```
I believe examples/automation-account is from the azurecaf project but I'm not sure why me updating examples/main/modules.tf would cause the above error.  What do you suggest I do?

**Comment by Shr3ps** [comment]
> > About the example, I mean it would be nice if you can update the `examples/main/modules.tf` file (and run pre-commit again for the README update) with the elements you put in the issue. It will be helpful for users/people who use our module.
> 
> I apologize because I am not very familiar with pre-commit errors mentioning files outside this git project like the following:
> 
> ```
> $ git commit -am 'chore: update example for custom domains'
> trim trailing whitespace................................................................Passed
> fix end of files........................................................................Passed
> check json..........................................................(no files to check)Skipped
> check yaml..........................................................(no files to check)Skipped
> check for broken symlinks...........................................(no files to check)Skipped
> check for added large files.............................................................Passed
> detect private key......................................................................Passed
> Terraform fmt...........................................................................Passed
> Terraform docs......................................................(no files to check)Skipped
> Terraform validate..................................................(no files to check)Skipped
> Terraform validate with tflint......................................(no files to check)Skipped
> Terraform validate with tfsec (deprecated, use "terraform_trivy").......................Passed
> error: invalid object 100644 496b1048c932a54707cbd671fb29e27c16197509 for 'examples/automation-account/README.md'
> error: Error building trees
> ```
> 
> I believe examples/automation-account is from the azurecaf project but I'm not sure why me updating examples/main/modules.tf would cause the above error. What do you suggest I do?

Hum very weird error, never got that. Maybe bypass pre-commit with the  --no-verify param for this one?

**Review by Shr3ps — APPROVED** [review]

**Review by zfiel — APPROVED** [review]

**Pull request merged**
